name = "Classitek"
author = "Piper McCorkle <contact@piperswe.me>"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abd427023ac8c9fc83a595475af0b2b18b47f0305110a40fac04788f5bb6cb7c"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6-beta.1"
