name = "Classitek"
author = "Piper McCorkle <contact@piperswe.me>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4ab412d130b2313ccba6e2da3aad24cece24f64228314bda2c52474bbe4f518"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6-beta.1"
